---
- name: Setup Full Monitoring Stack with Multi-Tenancy & NAS Automation
  hosts: all
  become: yes

  vars:
    node_exporter_ver: "1.7.0"
    promtail_ver: "2.9.2"
    prometheus_ver: "2.48.0"
    loki_ver: "2.9.2"
    grafana_ver: "10.2.2"
    blackbox_exporter_ver: "0.24.0"

    admin_user: "ansible-admin"
    prometheus_user: "prometheus"
    minio_data_path: "/mnt/NAS/minio_data"
    minio_root_user: "minioadmin"
    minio_root_password: "minioadmin"
    monitoring_server_ip: "10.4.5.10" 

  tasks:
    #####################################################################
    # [공통] 시스템 유저 및 필수 패키지
    #####################################################################
    - name: Prometheus 시스템 유저 생성
      user:
        name: "{{ prometheus_user }}"
        system: yes
        shell: /sbin/nologin

    - name: 필수 패키지 설치
      dnf:
        name: [wget, tar, unzip, python3-libsemanage, net-tools]
        state: present

    #####################################################################
    # [섹션 1] 에이전트 설치 (모든 호스트)
    #####################################################################
    - name: 에이전트 바이너리 다운로드 및 압축 해제
      unarchive:
        src: "https://github.com/{{ item.url }}"
        dest: /tmp
        remote_src: yes
      loop:
        - { url: "prometheus/node_exporter/releases/download/v{{ node_exporter_ver }}/node_exporter-{{ node_exporter_ver }}.linux-amd64.tar.gz" }
        - { url: "grafana/loki/releases/download/v{{ promtail_ver }}/promtail-linux-amd64.zip" }

    - name: 에이전트 바이너리 배치
      copy:
        src: "{{ item.src }}"
        dest: "/usr/local/bin/{{ item.dest }}"
        mode: '0755'
        owner: "{{ admin_user }}"
        group: "{{ admin_user }}"
        remote_src: yes
      loop:
        - { src: "/tmp/node_exporter-{{ node_exporter_ver }}.linux-amd64/node_exporter", dest: "node_exporter" }
        - { src: "/tmp/promtail-linux-amd64", dest: "promtail" }

    #####################################################################
    # [섹션 2] 모니터링 서버 전용 스택 (monitoring_server 그룹 전용)
    #####################################################################
    - name: 모니터링 메인 서버 블록
      when: "'monitoring_server' in group_names"
      block:
        - name: Grafana RPM 설치
          dnf:
            name: "https://dl.grafana.com/oss/release/grafana-{{ grafana_ver }}-1.x86_64.rpm"
            state: present
            disable_gpg_check: yes

        - name: 시스템 디렉터리 생성
          file:
            path: "{{ item.path }}"
            state: directory
            owner: "{{ item.owner | default('root') }}"
            mode: '0755'
          loop:
            - { path: /etc/prometheus }
            - { path: /var/lib/prometheus, owner: "{{ prometheus_user }}" }
            - { path: /etc/grafana/provisioning/datasources }

        - name: NAS 데이터 디렉터리 생성 (충돌 방지 처리)
          file:
            path: "{{ minio_data_path }}"
            state: directory
            owner: "{{ admin_user }}"
            group: "{{ admin_user }}"
            mode: '0775'
          become: no

        - name: 메인 서버 바이너리 다운로드
          get_url:
            url: "https://dl.min.io/server/minio/release/linux-amd64/minio"
            dest: "/usr/local/bin/minio"
            mode: '0755'

        - name: 메인 스택 압축 해제
          unarchive:
            src: "{{ item.url }}"
            dest: /tmp
            remote_src: yes
          loop:
            - { url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_ver }}/prometheus-{{ prometheus_ver }}.linux-amd64.tar.gz" }
            - { url: "https://github.com/grafana/loki/releases/download/v{{ loki_ver }}/loki-linux-amd64.zip" }
            - { url: "https://github.com/prometheus/blackbox_exporter/releases/download/v{{ blackbox_exporter_ver }}/blackbox_exporter-{{ blackbox_exporter_ver }}.linux-amd64.tar.gz" }

        - name: 바이너리 이동
          shell: |
            cp /tmp/prometheus-{{ prometheus_ver }}.linux-amd64/prometheus /usr/local/bin/
            cp /tmp/loki-linux-amd64 /usr/local/bin/loki
            cp /tmp/blackbox_exporter-{{ blackbox_exporter_ver }}.linux-amd64/blackbox_exporter /usr/local/bin/
            chmod +x /usr/local/bin/{prometheus,loki,blackbox_exporter}

    #####################################################################
    # [섹션 3] 설정 파일 배포
    #####################################################################
    - name: 모든 서버 공통 설정 배포
      template:
        src: "templates/{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - { src: node_exporter.service.j2, dest: /etc/systemd/system/node_exporter.service }
        - { src: promtail.service.j2, dest: /etc/systemd/system/promtail.service }
        - { src: promtail-config.yml.j2, dest: /etc/promtail-config.yml }

    - name: 모니터링 서버 전용 설정 배포
      template:
        src: "templates/{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - { src: prometheus.service.j2, dest: /etc/systemd/system/prometheus.service }
        - { src: prometheus.yml.j2, dest: /etc/prometheus/prometheus.yml }
        - { src: loki.service.j2, dest: /etc/systemd/system/loki.service }
        - { src: loki-config.yml.j2, dest: /etc/loki-config.yaml }
        - { src: blackbox_exporter.service.j2, dest: /etc/systemd/system/blackbox_exporter.service }
        - { src: minio.service.j2, dest: /etc/systemd/system/minio.service }
        - { src: loki-datasource.yml.j2, dest: /etc/grafana/provisioning/datasources/loki.yaml }
      when: "'monitoring_server' in group_names"

    #####################################################################
    # [섹션 4] 서비스 가동 및 초기화 (실행 범위 수정 완료)
    #####################################################################
    - name: systemd 데몬 리로드
      systemd:
        daemon_reload: yes

    - name: 모든 서비스 시작 및 활성화
      systemd:
        name: "{{ item.name }}"
        state: restarted
        enabled: yes
      loop:
        - { name: node_exporter, server_only: false }
        - { name: promtail, server_only: false }
        - { name: minio, server_only: true }
        - { name: loki, server_only: true }
        - { name: prometheus, server_only: true }
        - { name: grafana-server, server_only: true }
        - { name: blackbox_exporter, server_only: true }
      when: >
        (not item.server_only) or 
        ('monitoring_server' in group_names)

    - name: MinIO 버킷 자동 생성
      shell: |
        curl -s https://dl.min.io/client/mc/release/linux-amd64/mc -o /usr/local/bin/mc
        chmod +x /usr/local/bin/mc
        /usr/local/bin/mc alias set myminio http://127.0.0.1:9000 {{ minio_root_user }} {{ minio_root_password }}
        /usr/local/bin/mc mb myminio/loki-data --ignore-existing
      when: "'monitoring_server' in group_names"
      ignore_errors: yes
