---
- name: Setup Full Monitoring Stack (Server & Agents)
  hosts: all
  become: yes

  # 1. 변수 설정 (중앙 집중 관리)
  vars:
    # 버전 정보
    node_exporter_ver: "1.7.0"
    promtail_ver: "2.9.2"
    prometheus_ver: "2.48.0"
    loki_ver: "2.9.2"
    grafana_ver: "10.2.2"
    blackbox_exporter_ver: "0.24.0"

    # 실행 환경 설정 (j2 템플릿에서 사용된 변수들)
    admin_user: "ansible-admin"
    prometheus_user: "prometheus"
    prometheus_port: 9090
    loki_port: 3100
    blackbox_exporter_port: 9115
    promtail_port: 9080

  tasks:
    #####################################################################
    # [공통] 시스템 유저 및 필수 패키지
    #####################################################################
    - name: Prometheus 시스템 유저 생성
      user:
        name: "{{ prometheus_user }}"
        system: yes
        shell: /sbin/nologin

    - name: 필수 패키지 설치
      dnf:
        name: [wget, tar, unzip, python3-libsemanage, net-tools]
        state: present

    #####################################################################
    # [섹션 1] 에이전트 설치 (모든 호스트: Node Exporter, Promtail)
    #####################################################################
    - name: 에이전트 바이너리 다운로드 및 압축 해제
      unarchive:
        src: "https://github.com/{{ item.url }}"
        dest: /tmp
        remote_src: yes
      loop:
        - { url: "prometheus/node_exporter/releases/download/v{{ node_exporter_ver }}/node_exporter-{{ node_exporter_ver }}.linux-amd64.tar.gz" }
        - { url: "grafana/loki/releases/download/v{{ promtail_ver }}/promtail-linux-amd64.zip" }

    - name: 에이전트 바이너리 배치
      copy:
        src: "{{ item.src }}"
        dest: "/usr/local/bin/{{ item.dest }}"
        mode: '0755'
        owner: "{{ admin_user }}"
        group: "{{ admin_user }}"
        remote_src: yes
      loop:
        - { src: "/tmp/node_exporter-{{ node_exporter_ver }}.linux-amd64/node_exporter", dest: "node_exporter" }
        - { src: "/tmp/promtail-linux-amd64", dest: "promtail" }

    #####################################################################
    # [섹션 2] 모니터링 서버 전용 스택 (Prometheus, Loki, Grafana, Blackbox)
    #####################################################################
    - name: 모니터링 메인 서버 설정 블록
      when: inventory_hostname in groups.get('monitoring_server', [])
      block:
        - name: Grafana RPM 설치
          dnf:
            name: "https://dl.grafana.com/oss/release/grafana-{{ grafana_ver }}-1.x86_64.rpm"
            state: present
            disable_gpg_check: yes

        - name: 모니터링 디렉터리 생성
          file:
            path: "{{ item.path }}"
            state: directory
            owner: "{{ item.owner | default('root') }}"
            group: "{{ item.group | default('root') }}"
            mode: '0755'
          loop:
            - { path: /etc/prometheus }
            - { path: /var/lib/prometheus, owner: "{{ prometheus_user }}", group: "{{ prometheus_user }}" }
            - { path: /etc/grafana/provisioning/datasources }

        - name: 메인 스택 바이너리 다운로드 및 압축 해제
          unarchive:
            src: "https://github.com/{{ item.url }}"
            dest: "/tmp"
            remote_src: yes
          loop:
            - { url: "prometheus/prometheus/releases/download/v{{ prometheus_ver }}/prometheus-{{ prometheus_ver }}.linux-amd64.tar.gz" }
            - { url: "grafana/loki/releases/download/v{{ loki_ver }}/loki-linux-amd64.zip" }
            - { url: "prometheus/blackbox_exporter/releases/download/v{{ blackbox_exporter_ver }}/blackbox_exporter-{{ blackbox_exporter_ver }}.linux-amd64.tar.gz" }

        - name: 메인 스택 바이너리 배치
          copy:
            src: "{{ item.src }}"
            dest: "/usr/local/bin/{{ item.dest }}"
            mode: '0755'
            remote_src: yes
          loop:
            - { src: "/tmp/loki-linux-amd64", dest: "loki" }
            - { src: "/tmp/prometheus-{{ prometheus_ver }}.linux-amd64/prometheus", dest: "prometheus" }
            - { src: "/tmp/blackbox_exporter-{{ blackbox_exporter_ver }}.linux-amd64/blackbox_exporter", dest: "blackbox_exporter" }

        - name: Loki 기본 설정 파일 다운로드 (초기값)
          get_url:
            url: "https://raw.githubusercontent.com/grafana/loki/v{{ loki_ver }}/cmd/loki/loki-local-config.yaml"
            dest: /etc/loki-config.yaml

    #####################################################################
    # [섹션 3] 설정 파일 배포 (우리가 수정한 j2 템플릿 적용)
    #####################################################################
    - name: 공통 에이전트 설정 배포 (모든 서버)
      template:
        src: "templates/{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - { src: node_exporter.service.j2, dest: /etc/systemd/system/node_exporter.service }
        - { src: promtail.service.j2, dest: /etc/systemd/system/promtail.service }
        - { src: promtail-config.yml.j2, dest: /etc/promtail-config.yml }

    - name: 모니터링 서버 전용 설정 배포
      template:
        src: "templates/{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - { src: prometheus.service.j2, dest: /etc/systemd/system/prometheus.service }
        - { src: prometheus.yml.j2, dest: /etc/prometheus/prometheus.yml }
        - { src: loki.service.j2, dest: /etc/systemd/system/loki.service }
        - { src: blackbox_exporter.service.j2, dest: /etc/systemd/system/blackbox_exporter.service }
      when: inventory_hostname in groups.get('monitoring_server', [])

    #####################################################################
    # [섹션 4] 실행 및 방화벽
    #####################################################################
    - name: 방화벽 포트 개방
      firewalld:
        port: "{{ item }}/tcp"
        permanent: yes
        state: enabled
      loop: [9090, 3000, 3100, 9100, 9080, 9115]
      notify: Reload Firewall

    - name: 모든 서비스 시작 및 활성화
      systemd:
        name: "{{ item.name }}"
        state: restarted
        enabled: yes
        daemon_reload: yes
      loop:
        - { name: node_exporter, server_only: false }
        - { name: promtail, server_only: false }
        - { name: prometheus, server_only: true }
        - { name: loki, server_only: true }
        - { name: grafana-server, server_only: true }
        - { name: blackbox_exporter, server_only: true }
      when: >
        (not item.server_only) or 
        (inventory_hostname in groups.get('monitoring_server', []))

  handlers:
    - name: Reload Firewall
      service:
        name: firewalld
        state: reloaded
